//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphRemake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSGBoxResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSGBoxResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphRemake.Properties.MSGBoxResource", typeof(MSGBoxResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrany plik zawiera niepoprawne dane.
        /// </summary>
        internal static string MSG_Failure_Content {
            get {
                return ResourceManager.GetString("MSG_Failure_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędny plik.
        /// </summary>
        internal static string MSG_Failure_Title {
            get {
                return ResourceManager.GetString("MSG_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie załadowano stan grafu.
        /// </summary>
        internal static string MSG_Success_Content {
            get {
                return ResourceManager.GetString("MSG_Success_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik załadowany.
        /// </summary>
        internal static string MSG_Success_Title {
            get {
                return ResourceManager.GetString("MSG_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruszaj.
        /// </summary>
        internal static string SEL_Cursor_Move {
            get {
                return ResourceManager.GetString("SEL_Cursor_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz.
        /// </summary>
        internal static string SEL_Cursor_Selecet {
            get {
                return ResourceManager.GetString("SEL_Cursor_Selecet", resourceCulture);
            }
        }
    }
}
